name: TypeScript Type Check
run-name: |
  Type Check for `${{ github.ref_name }}`
  ${{ github.event_name == 'pull_request' && format('PR: {}', github.event.pull_request.number) }}

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@5

      - name: Setup Bun
        uses: oven-sh/bun@v2
        with:
          bun-version: stable

      - name: Install dependencies
        run: bun install

      - name: Type check packages
        run: |
          set -e
          for pkg in packages/*; do
            if [ -f "$pkg/tsconfig.json" ]; then
              echo "Type checking for `$pkg...`"
              bun tsc --noEmit -p "$pkg"
            fi
          done
