name: TypeScript Type Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Type check packages
        run: |
          set -e
          for pkg in packages/*; do
            if [ -f "$pkg/tsconfig.json" ]; then
              echo "Type checking for $pkg..."
              bun tsc --noEmit -p "$pkg"
            fi
          done
